module.exports = [ { word: 'ankle', stress: '1/0' },
  { word: 'arm', stress: '1' },
  { word: 'back', stress: '1' },
  { word: 'belly', stress: '1/0' },
  { word: 'bottom', stress: '1/0' },
  { word: 'breast', stress: '1' },
  { word: 'buttocks', stress: '1/0' },
  { word: 'calf', stress: '1' },
  { word: 'cheek', stress: '1' },
  { word: 'chin', stress: '1' },
  { word: 'ear', stress: '1' },
  { word: 'elbow', stress: '1/1' },
  { word: 'eye', stress: '1' },
  { word: 'eyebrow', stress: '1/1' },
  { word: 'eyelash', stress: '1/1' },
  { word: 'finger', stress: '1/0' },
  { word: 'fist', stress: '1' },
  { word: 'foot', stress: '1' },
  { word: 'forearm', stress: '0/1' },
  { word: 'forehead', stress: '1/0' },
  { word: 'hair', stress: '1' },
  { word: 'hand', stress: '1' },
  { word: 'head', stress: '1' },
  { word: 'hip', stress: '1' },
  { word: 'knee', stress: '1' },
  { word: 'leg', stress: '1' },
  { word: 'lip', stress: '1' },
  { word: 'lower leg', stress: '1/0 1' },
  { word: 'mouth', stress: '1' },
  { word: 'neck', stress: '1' },
  { word: 'nose', stress: '1' },
  { word: 'nostril', stress: '1/1' },
  { word: 'shoulder', stress: '1/0' },
  { word: 'thigh', stress: '1' },
  { word: 'thumb', stress: '1' },
  { word: 'toe', stress: '1' },
  { word: 'tongue', stress: '1' },
  { word: 'tooth', stress: '1' },
  { word: 'upper arm', stress: '1/0 1' },
  { word: 'waist', stress: '1' },
  { word: 'wrist', stress: '1' } ];
